# Generated by Django 2.0.1 on 2018-03-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='worksheets',
            field=models.ManyToManyField(blank=True, to='worksheet.WorkSheet'),
        ),
    ]
