# Generated by Django 2.0.1 on 2018-03-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='question_images')),
                ('classroom', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V')], max_length=2)),
                ('difficulty', models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=1)),
                ('question_type', models.CharField(choices=[('value', 'Short Answer'), ('fill_blank', 'Fill in the blanks'), ('mcq', 'Mulitple Choice'), ('lhs_rhs', 'Left Right Matching')], max_length=10)),
                ('options', models.TextField(blank=True)),
                ('answer', models.TextField()),
                ('solution', models.TextField(blank=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schoolquestion', to='members.School')),
                ('subtopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.SubTopic')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
