# Generated by Django 2.0.1 on 2018-03-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qapp', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qapp.Questions')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.School')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.SubTopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharingWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('flag', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to='members.Profile')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='members.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('classroom', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V')], max_length=2)),
                ('category', models.CharField(choices=[('testing', 'Test'), ('practice', 'Practice'), ('homework', 'Home Work'), ('quiz', 'Quiz'), ('classwork', 'Class-Work')], max_length=10)),
                ('duration', models.PositiveIntegerField()),
                ('due_date', models.DateTimeField()),
                ('question', models.ManyToManyField(related_name='wsheets', to='qapp.Questions')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.School')),
                ('subtopic', models.ManyToManyField(blank=True, to='members.SubTopic')),
                ('topic', models.ManyToManyField(to='members.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sharingws',
            name='worksheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worksheet.WorkSheet'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='worksheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheet.WorkSheet'),
        ),
    ]
